In [33]:
import pandas as pd

In [34]:
airplane = pd.read_csv('aviation_accidents_detailed.csv')

In [35]:
airplane.head()

,Date,Type,Registration,Operator,Fatalities,Location,Detail URL,Time,Owner/operator,MSN,...,Investigating agency,Unnamed: 25,Investigating agency,Report number,Status,Duration,Download report,Total airframe hrs,Cycles,Report
0,Tuesday 2 January 1990,CASA/Nurtanio NC-212 Aviocar 200,PK-PCM,Pelita Air Service,Fatalities: 9 / Occupants: 16,"Banten Bay, Java Sea - Indonesia",https://aviation-safety.net/wikibase/326130,13:40,Pelita Air Service,217/57N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tuesday 2 January 1990,McDonnell Douglas DC-10-10,N109AA,American Airlines,Fatalities: 0 / Occupants: 257,"Baltimore, MD - United States of America",https://aviation-safety.net/wikibase/367551,01:07 LT,American Airlines,46509/21,...,NTSB,NaN,NTSB,BFO90FA017,Investigation completed,2 years and 11 months,Final report,NaN,NaN,NaN
2,Wednesday 3 January 1990,Britten-Norman BN-2A Trislander Mk.III,YJ-RV3,Vanair,Fatalities: 0 / Occupants:,15 km from Port Vila-Bauerfield Airport (VLI) ...,https://aviation-safety.net/wikibase/326129,NaN,Vanair,0349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Thursday 4 January 1990,Fairchild SA227-AC Metro III,N31138,"USAir Express, opb Chautauqua Airlines",Fatalities: 0 / Occupants: 0,"Hagerstown, MD - United States of America",https://aviation-safety.net/wikibase/326128,NaN,"USAir Express, opb Chautauqua Airlines",AC-579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Friday 5 January 1990,Fokker F-28 Fellowship 4000,LV-MZD,Aerolineas Argentinas,Fatalities: 0 / Occupants: 90,"Villa Gesell Airport, BA (VLG) - Argentina",https://aviation-safety.net/wikibase/326126,21:50,Aerolineas Argentinas,11127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23915 hours,32264 flights,NaN

In [36]:
airplane[['Fatalities', 'Occupants']] = airplane['Fatalities'].str.extract(r'Fatalities:\s*(\d+)\s*/\s*Occupants:\s*(\d+)', expand=True)

# Convert them to numeric types
airplane['Fatalities'] = pd.to_numeric(airplane['Fatalities'], errors='coerce')
airplane['Occupants'] = pd.to_numeric(airplane['Occupants'], errors='coerce')

In [37]:
airplane

,Date,Type,Registration,Operator,Fatalities,Location,Detail URL,Time,Owner/operator,MSN,...,Unnamed: 25,Investigating agency,Report number,Status,Duration,Download report,Total airframe hrs,Cycles,Report,Occupants
0,Tuesday 2 January 1990,CASA/Nurtanio NC-212 Aviocar 200,PK-PCM,Pelita Air Service,9.0,"Banten Bay, Java Sea - Indonesia",https://aviation-safety.net/wikibase/326130,13:40,Pelita Air Service,217/57N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0
1,Tuesday 2 January 1990,McDonnell Douglas DC-10-10,N109AA,American Airlines,0.0,"Baltimore, MD - United States of America",https://aviation-safety.net/wikibase/367551,01:07 LT,American Airlines,46509/21,...,NaN,NTSB,BFO90FA017,Investigation completed,2 years and 11 months,Final report,NaN,NaN,NaN,257.0
2,Wednesday 3 January 1990,Britten-Norman BN-2A Trislander Mk.III,YJ-RV3,Vanair,NaN,15 km from Port Vila-Bauerfield Airport (VLI) ...,https://aviation-safety.net/wikibase/326129,NaN,Vanair,0349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Thursday 4 January 1990,Fairchild SA227-AC Metro III,N31138,"USAir Express, opb Chautauqua Airlines",0.0,"Hagerstown, MD - United States of America",https://aviation-safety.net/wikibase/326128,NaN,"USAir Express, opb Chautauqua Airlines",AC-579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,Friday 5 January 1990,Fokker F-28 Fellowship 4000,LV-MZD,Aerolineas Argentinas,0.0,"Villa Gesell Airport, BA (VLG) - Argentina",https://aviation-safety.net/wikibase/326126,21:50,Aerolineas Argentinas,11127,...,NaN,NaN,NaN,NaN,NaN,NaN,23915 hours,32264 flights,NaN,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9777,Thursday 9 January 2025,Cessna 525 CitationJet CJ1+,PR-GFS,Private,1.0,"Ubatuba Airport, SP (UBT/SDUB) - Brazil",https://aviation-safety.net/wikibase/470557,10:05,Private,525-0663,...,NaN,CENIPA,NaN,Preliminary report,NaN,Preliminary report,NaN,NaN,NaN,5.0
9778,Tuesday 7 January 2025,Boeing 787-9 Dreamliner,JA892A,All Nippon Airways - ANA,0.0,"near Ojai, CA - United States of America",https://aviation-safety.net/wikibase/473910,17:40,All Nippon Airways - ANA,34513/571,...,NaN,NTSB,DCA25LA102,Preliminary report,4 months,Preliminary report,NaN,NaN,NaN,196.0
9779,Tuesday 7 January 2025,Cessna 208 Caravan 675,VH-WTY,Swan River Seaplanes,3.0,"off Rottnest Island, near Thomson Bay, WA - Au...",https://aviation-safety.net/wikibase/470116,16:00 LT,Swan River Seaplanes,20800586,...,NaN,ATSB,AO-2025-001,Preliminary report,1 month,Preliminary report,NaN,NaN,NaN,7.0
9780,Friday 3 January 2025,Cirrus SF50 Vision Jet G2,N603AP,Foxtrot Jet LLC,0.0,Black Hills Airport-Clyde Ice Field (SPF/KSPF)...,https://aviation-safety.net/wikibase/470067,23:38,Foxtrot Jet LLC,0057,...,NaN,NTSB,CEN25LA069,Preliminary report,NaN,Preliminary report,NaN,NaN,NaN,6.0
9781,Thursday 2 January 2025,Bombardier CRJ-200LR,N438SW,Corporate Flight Management Inc dba Contour Av...,0.0,"Stringtown, MS - United States of America",https://aviation-safety.net/wikibase/469640,18:54,Corporate Flight Management Inc dba Contour Av...,7574,...,NaN,NTSB,CEN25LA070,Investigation completed,1 month,Final report,NaN,NaN,NaN,32.0

In [38]:
airplane.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9782 entries, 0 to 9781
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  9782 non-null   object
 1   Type                  9782 non-null   object
 2   Registration          9414 non-null   object
 3   Operator              9726 non-null   object
 4   Fatalities            8613 non-null   float64
 5   Location              9782 non-null   object
 6   Detail URL            9782 non-null   object
 7   Time                  7331 non-null   object
 8   Owner/operator        9724 non-null   object
 9   MSN                   9318 non-null   object
 10  Year of manufacture   8775 non-null   float64
 11  Other fatalities      9780 non-null   float64
 12  Aircraft damage       8660 non-null   object
 13  Category              9712 non-null   object
 14  Phase                 9779 non-null   object
 15  Nature                9776 non-null   object
 16  Departure airport     8495 non-null   object
 17  Destination airport   8516 non-null   object
 18  Confidence Rating     7678 non-null   object
 19  ASN Home              9782 non-null   object
 20  FSF Home              9782 non-null   object
 21  Contact Us            9782 non-null   object
 22  Press / Media         0 non-null      float64
 23  Engine model          7268 non-null   object
 24  Investigating agency  5141 non-null   object
 25  Unnamed: 25           0 non-null      float64
 26  Investigating agency  4752 non-null   object
 27  Report number         4346 non-null   object
 28  Status                4803 non-null   object
 29  Duration              3962 non-null   object
 30  Download report       4794 non-null   object
 31  Total airframe hrs    3476 non-null   object
 32  Cycles                1057 non-null   object
 33  Report                9 non-null      object
 34  Occupants             8613 non-null   float64
dtypes: float64(6), object(29)
memory usage: 2.6+ MB

In [39]:
airplane['Date'] = pd.to_datetime(airplane['Date'], errors='coerce')

In [40]:
airplane = airplane.sort_values(by='Date')

In [41]:
airplane.tail()

,Date,Type,Registration,Operator,Fatalities,Location,Detail URL,Time,Owner/operator,MSN,...,Unnamed: 25,Investigating agency,Report number,Status,Duration,Download report,Total airframe hrs,Cycles,Report,Occupants
8333,NaT,Rockwell Sabreliner 80,N337KL,private,0.0,"Eugene Airport, OR (EUG) - United States of Am...",https://aviation-safety.net/wikibase/319513,NaN,private,380-71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8877,NaT,Antonov An-2,NaN,Korean People's Army Air and Anti-Air Force (K...,5.0,near Taechon Air Base - North Korea,https://aviation-safety.net/wikibase/319050,NaN,Korean People's Army Air and Anti-Air Force (K...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
9181,NaT,Antonov An-2R,RA-17951,Voskhod LLC,NaN,near Oymyakon Airfield - Russia,https://aviation-safety.net/wikibase/318792,NaN,Voskhod LLC,1G206-56,...,NaN,MAK,NaN,Investigation completed,53 years and 11 months,Final report,6750 hours,NaN,NaN,NaN
9458,NaT,Boeing 777-328ER,F-GSQT,Air France,NaN,Paris-Charles de Gaulle Airport (CDG/LFPG) - F...,https://aviation-safety.net/wikibase/345112,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9459,NaT,Airbus A330-941,N411DX,Delta Air Lines,NaN,Paris-Charles de Gaulle Airport (CDG/LFPG) - F...,https://aviation-safety.net/wikibase/345113,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
airplane.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9782 entries, 0 to 9459
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  9646 non-null   datetime64[ns]
 1   Type                  9782 non-null   object
 2   Registration          9414 non-null   object
 3   Operator              9726 non-null   object
 4   Fatalities            8613 non-null   float64
 5   Location              9782 non-null   object
 6   Detail URL            9782 non-null   object
 7   Time                  7331 non-null   object
 8   Owner/operator        9724 non-null   object
 9   MSN                   9318 non-null   object
 10  Year of manufacture   8775 non-null   float64
 11  Other fatalities      9780 non-null   float64
 12  Aircraft damage       8660 non-null   object
 13  Category              9712 non-null   object
 14  Phase                 9779 non-null   object
 15  Nature                9776 non-null   object
 16  Departure airport     8495 non-null   object
 17  Destination airport   8516 non-null   object
 18  Confidence Rating     7678 non-null   object
 19  ASN Home              9782 non-null   object
 20  FSF Home              9782 non-null   object
 21  Contact Us            9782 non-null   object
 22  Press / Media         0 non-null      float64
 23  Engine model          7268 non-null   object
 24  Investigating agency  5141 non-null   object
 25  Unnamed: 25           0 non-null      float64
 26  Investigating agency  4752 non-null   object
 27  Report number         4346 non-null   object
 28  Status                4803 non-null   object
 29  Duration              3962 non-null   object
 30  Download report       4794 non-null   object
 31  Total airframe hrs    3476 non-null   object
 32  Cycles                1057 non-null   object
 33  Report                9 non-null      object
 34  Occupants             8613 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(28)
memory usage: 2.7+ MB

In [45]:
airplane = airplane.dropna(subset=['Date'])

In [46]:
airplane

,Date,Type,Registration,Operator,Fatalities,Location,Detail URL,Time,Owner/operator,MSN,...,Unnamed: 25,Investigating agency,Report number,Status,Duration,Download report,Total airframe hrs,Cycles,Report,Occupants
0,1990-01-02,CASA/Nurtanio NC-212 Aviocar 200,PK-PCM,Pelita Air Service,9.0,"Banten Bay, Java Sea - Indonesia",https://aviation-safety.net/wikibase/326130,13:40,Pelita Air Service,217/57N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0
1,1990-01-02,McDonnell Douglas DC-10-10,N109AA,American Airlines,0.0,"Baltimore, MD - United States of America",https://aviation-safety.net/wikibase/367551,01:07 LT,American Airlines,46509/21,...,NaN,NTSB,BFO90FA017,Investigation completed,2 years and 11 months,Final report,NaN,NaN,NaN,257.0
2,1990-01-03,Britten-Norman BN-2A Trislander Mk.III,YJ-RV3,Vanair,NaN,15 km from Port Vila-Bauerfield Airport (VLI) ...,https://aviation-safety.net/wikibase/326129,NaN,Vanair,0349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1990-01-04,Fairchild SA227-AC Metro III,N31138,"USAir Express, opb Chautauqua Airlines",0.0,"Hagerstown, MD - United States of America",https://aviation-safety.net/wikibase/326128,NaN,"USAir Express, opb Chautauqua Airlines",AC-579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,1990-01-05,Fokker F-28 Fellowship 4000,LV-MZD,Aerolineas Argentinas,0.0,"Villa Gesell Airport, BA (VLG) - Argentina",https://aviation-safety.net/wikibase/326126,21:50,Aerolineas Argentinas,11127,...,NaN,NaN,NaN,NaN,NaN,NaN,23915 hours,32264 flights,NaN,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9724,2025-06-06,Let L-410UVP-E9,TG-TJG,Inversiones 777 S.A.,3.0,near Pavencul - Mexico,https://aviation-safety.net/wikibase/517655,NaN,Inversiones 777 S.A.,902419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
9723,2025-06-08,de Havilland Canada DHC-6 Twin Otter 100,N166DH,"Randigo LLC, opf Skydive Tennessee",0.0,near Tullahoma Regional Airport/William Northe...,https://aviation-safety.net/wikibase/518040,c. 12:30 LT,"Randigo LLC, opf Skydive Tennessee",66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0
9722,2025-06-08,Boeing 737 MAX 8,N27266,United Airlines,0.0,"Phoenix-Sky Harbor International Airport, AZ (...",https://aviation-safety.net/wikibase/518978,14:03 UTC,United Airlines,66597/8153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0
9721,2025-06-10,Antonov An-2TP,RA-81532,RegionAvia opb MiAn airline,0.0,Tomponsky ulus (district) of Yakutia - Russia,https://aviation-safety.net/wikibase/518320,11:48,RegionAvia opb MiAn airline,1G208-36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
9720,2025-06-12,Boeing 787-8 Dreamliner,VT-ANB,Air India,241.0,near Sardar Vallabhbhai Patel International Ap...,https://aviation-safety.net/wikibase/518859,c. 13:40 LT,Air India,36279/26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0