In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8,])

In [4]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
dates = pd.date_range("20130101", periods = 6)

In [6]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [8]:
df

                   A         B         C         D
2013-01-01 -0.934580  0.590852 -0.521059  0.579629
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055
2013-01-04  1.124484 -0.589912 -2.847483  1.567676
2013-01-05 -0.957137  0.550070 -0.461738  0.794312
2013-01-06 -0.221867 -1.565888  1.461616  0.452483

In [9]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [10]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [11]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [12]:
df.head()

                   A         B         C         D
2013-01-01 -0.934580  0.590852 -0.521059  0.579629
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055
2013-01-04  1.124484 -0.589912 -2.847483  1.567676
2013-01-05 -0.957137  0.550070 -0.461738  0.794312

In [13]:
df.tail(3)

                   A         B         C         D
2013-01-04  1.124484 -0.589912 -2.847483  1.567676
2013-01-05 -0.957137  0.550070 -0.461738  0.794312
2013-01-06 -0.221867 -1.565888  1.461616  0.452483

In [14]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [15]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [16]:
df.to_numpy()

array([[-0.93458042,  0.59085173, -0.52105921,  0.57962883],
       [-0.44831283, -1.33971874, -0.57118332,  2.03907803],
       [-1.32844311, -0.0164011 ,  1.28691983, -0.69905543],
       [ 1.12448413, -0.58991178, -2.84748252,  1.5676755 ],
       [-0.95713672,  0.55007038, -0.46173801,  0.79431165],
       [-0.22186717, -1.56588798,  1.46161648,  0.4524828 ]])

In [17]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [18]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [19]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.460976 -0.395166 -0.275488  0.789020
std    0.871090  0.928425  1.565646  0.952937
min   -1.328443 -1.565888 -2.847483 -0.699055
25%   -0.951498 -1.152267 -0.558652  0.484269
50%   -0.691447 -0.303156 -0.491399  0.686970
75%   -0.278479  0.408453  0.849755  1.374335
max    1.124484  0.590852  1.461616  2.039078

In [20]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.934580   -0.448313   -1.328443    1.124484   -0.957137   -0.221867
B    0.590852   -1.339719   -0.016401   -0.589912    0.550070   -1.565888
C   -0.521059   -0.571183    1.286920   -2.847483   -0.461738    1.461616
D    0.579629    2.039078   -0.699055    1.567676    0.794312    0.452483

In [21]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  0.579629 -0.521059  0.590852 -0.934580
2013-01-02  2.039078 -0.571183 -1.339719 -0.448313
2013-01-03 -0.699055  1.286920 -0.016401 -1.328443
2013-01-04  1.567676 -2.847483 -0.589912  1.124484
2013-01-05  0.794312 -0.461738  0.550070 -0.957137
2013-01-06  0.452483  1.461616 -1.565888 -0.221867

In [22]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-06 -0.221867 -1.565888  1.461616  0.452483
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078
2013-01-04  1.124484 -0.589912 -2.847483  1.567676
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055
2013-01-05 -0.957137  0.550070 -0.461738  0.794312
2013-01-01 -0.934580  0.590852 -0.521059  0.579629

In [23]:
df["A"]

2013-01-01   -0.934580
2013-01-02   -0.448313
2013-01-03   -1.328443
2013-01-04    1.124484
2013-01-05   -0.957137
2013-01-06   -0.221867
Freq: D, Name: A, dtype: float64

In [24]:
df[0:3]

                   A         B         C         D
2013-01-01 -0.934580  0.590852 -0.521059  0.579629
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055

In [25]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055
2013-01-04  1.124484 -0.589912 -2.847483  1.567676

In [26]:
df.loc[dates[0]]

A   -0.934580
B    0.590852
C   -0.521059
D    0.579629
Name: 2013-01-01 00:00:00, dtype: float64

In [27]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01 -0.934580  0.590852
2013-01-02 -0.448313 -1.339719
2013-01-03 -1.328443 -0.016401
2013-01-04  1.124484 -0.589912
2013-01-05 -0.957137  0.550070
2013-01-06 -0.221867 -1.565888

In [28]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02 -0.448313 -1.339719
2013-01-03 -1.328443 -0.016401
2013-01-04  1.124484 -0.589912

In [29]:
df.loc[dates[0], "A"]

-0.9345804214786414

In [30]:
df.at[dates[0], "A"]

-0.9345804214786414

In [31]:
df.iloc[3]

A    1.124484
B   -0.589912
C   -2.847483
D    1.567676
Name: 2013-01-04 00:00:00, dtype: float64

In [32]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  1.124484 -0.589912
2013-01-05 -0.957137  0.550070

In [33]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2013-01-02 -0.448313 -0.571183
2013-01-03 -1.328443  1.286920
2013-01-05 -0.957137 -0.461738

In [34]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055

In [35]:
df.iloc[:, 1:3]

                   B         C
2013-01-01  0.590852 -0.521059
2013-01-02 -1.339719 -0.571183
2013-01-03 -0.016401  1.286920
2013-01-04 -0.589912 -2.847483
2013-01-05  0.550070 -0.461738
2013-01-06 -1.565888  1.461616

In [36]:
df.iloc[1, 1]

-1.3397187398445596

In [37]:
df.iat[1, 1]

-1.3397187398445596

In [38]:
df[df["A"] >  0]

                   A         B         C         D
2013-01-04  1.124484 -0.589912 -2.847483  1.567676

In [39]:
df[df > 0]

                   A         B         C         D
2013-01-01       NaN  0.590852       NaN  0.579629
2013-01-02       NaN       NaN       NaN  2.039078
2013-01-03       NaN       NaN  1.286920       NaN
2013-01-04  1.124484       NaN       NaN  1.567676
2013-01-05       NaN  0.550070       NaN  0.794312
2013-01-06       NaN       NaN  1.461616  0.452483

In [40]:
df2 = df.copy()

In [41]:
df2["E"] = ["one", "one", "two", "three", "four", "three"]

In [42]:
df2

                   A         B         C         D      E
2013-01-01 -0.934580  0.590852 -0.521059  0.579629    one
2013-01-02 -0.448313 -1.339719 -0.571183  2.039078    one
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055    two
2013-01-04  1.124484 -0.589912 -2.847483  1.567676  three
2013-01-05 -0.957137  0.550070 -0.461738  0.794312   four
2013-01-06 -0.221867 -1.565888  1.461616  0.452483  three

In [43]:
df2[df2["E"].isin(["two", "four"])]

                   A         B         C         D     E
2013-01-03 -1.328443 -0.016401  1.286920 -0.699055   two
2013-01-05 -0.957137  0.550070 -0.461738  0.794312  four

In [44]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

In [45]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [46]:
df["F"] = s1

In [47]:
df.at[dates[0], "A"] = 0

In [48]:
df.iat[0, 1] = 0

In [49]:
df.loc[:, "D"] = np.array([5] * len(df))

In [50]:
df

                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -0.521059  5.0  NaN
2013-01-02 -0.448313 -1.339719 -0.571183  5.0  1.0
2013-01-03 -1.328443 -0.016401  1.286920  5.0  2.0
2013-01-04  1.124484 -0.589912 -2.847483  5.0  3.0
2013-01-05 -0.957137  0.550070 -0.461738  5.0  4.0
2013-01-06 -0.221867 -1.565888  1.461616  5.0  5.0

In [51]:
df2 = df.copy()

In [52]:
df2[df2 > 0] = -df2

In [53]:
df2

                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -0.521059 -5.0  NaN
2013-01-02 -0.448313 -1.339719 -0.571183 -5.0 -1.0
2013-01-03 -1.328443 -0.016401 -1.286920 -5.0 -2.0
2013-01-04 -1.124484 -0.589912 -2.847483 -5.0 -3.0
2013-01-05 -0.957137 -0.550070 -0.461738 -5.0 -4.0
2013-01-06 -0.221867 -1.565888 -1.461616 -5.0 -5.0

In [54]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

In [55]:
df1.loc[dates[0] : dates[1], "E"] = 1

In [56]:
df1

                   A         B         C    D    F    E
2013-01-01  0.000000  0.000000 -0.521059  5.0  NaN  1.0
2013-01-02 -0.448313 -1.339719 -0.571183  5.0  1.0  1.0
2013-01-03 -1.328443 -0.016401  1.286920  5.0  2.0  NaN
2013-01-04  1.124484 -0.589912 -2.847483  5.0  3.0  NaN

In [57]:
df1.dropna(how="any")

                   A         B         C    D    F    E
2013-01-02 -0.448313 -1.339719 -0.571183  5.0  1.0  1.0

In [58]:
df1.fillna(value=5)

                   A         B         C    D    F    E
2013-01-01  0.000000  0.000000 -0.521059  5.0  5.0  1.0
2013-01-02 -0.448313 -1.339719 -0.571183  5.0  1.0  1.0
2013-01-03 -1.328443 -0.016401  1.286920  5.0  2.0  5.0
2013-01-04  1.124484 -0.589912 -2.847483  5.0  3.0  5.0

In [59]:
pd.isna(df1)

                A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [60]:
df.mean()

A   -0.305213
B   -0.493642
C   -0.275488
D    5.000000
F    3.000000
dtype: float64

In [61]:
df.mean(axis=1)

2013-01-01    1.119735
2013-01-02    0.728157
2013-01-03    1.388415
2013-01-04    1.137418
2013-01-05    1.626239
2013-01-06    1.934772
Freq: D, dtype: float64

In [62]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)

In [63]:
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [64]:
df.sub(s, axis="index")

                   A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -2.328443 -1.016401  0.286920  4.0  1.0
2013-01-04 -1.875516 -3.589912 -5.847483  2.0  0.0
2013-01-05 -5.957137 -4.449930 -5.461738  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [65]:
df.agg(lambda x: np.mean(x) * 5.6)

A    -1.709191
B    -2.764393
C    -1.542732
D    28.000000
F    16.800000
dtype: float64

In [66]:
df.transform(lambda x: x * 101.2)

                     A           B           C      D      F
2013-01-01    0.000000    0.000000  -52.731192  506.0    NaN
2013-01-02  -45.369258 -135.579536  -57.803752  506.0  101.2
2013-01-03 -134.438443   -1.659791  130.236287  506.0  202.4
2013-01-04  113.797793  -59.699072 -288.165231  506.0  303.6
2013-01-05  -96.862236   55.667122  -46.727887  506.0  404.8
2013-01-06  -22.452957 -158.467864  147.915588  506.0  506.0

In [67]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [68]:
s

0    1
1    3
2    5
3    4
4    0
5    2
6    0
7    1
8    4
9    5
dtype: int64

In [69]:
s.value_counts()

1    2
5    2
4    2
0    2
3    1
2    1
Name: count, dtype: int64

In [70]:
s = pd.Series(["A", "B", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

In [71]:
s.str.lower()

0       a
1       b
2    aaba
3    baca
4     NaN
5    caba
6     dog
7     cat
dtype: object

In [72]:
df = pd.DataFrame(np.random.randn(10, 4))

In [73]:
df

          0         1         2         3
0  1.054559 -1.496947 -0.864913 -0.802105
1  0.037033  0.995661 -1.432674 -1.539096
2 -2.646667  0.382824 -0.515442  0.353241
3  0.422822  0.059302  0.990922  0.164418
4  0.636212 -0.222983  0.042416 -0.639749
5 -0.668280  1.147377 -0.638392  0.218315
6  0.665670  0.587249  1.482650 -0.050416
7  2.555123  0.269252 -0.939187  0.151796
8 -0.237834  0.266415  1.081596  0.175571
9  0.197618 -0.885216 -0.588320  0.143699

In [74]:
pieces = [df[:3], df[3:7], df[7:]]

In [75]:
pd.concat(pieces)

          0         1         2         3
0  1.054559 -1.496947 -0.864913 -0.802105
1  0.037033  0.995661 -1.432674 -1.539096
2 -2.646667  0.382824 -0.515442  0.353241
3  0.422822  0.059302  0.990922  0.164418
4  0.636212 -0.222983  0.042416 -0.639749
5 -0.668280  1.147377 -0.638392  0.218315
6  0.665670  0.587249  1.482650 -0.050416
7  2.555123  0.269252 -0.939187  0.151796
8 -0.237834  0.266415  1.081596  0.175571
9  0.197618 -0.885216 -0.588320  0.143699

In [76]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

In [77]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [78]:
left

   key  lval
0  foo     1
1  foo     2

In [79]:
right

   key  rval
0  foo     4
1  foo     5

In [80]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [81]:
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})

In [82]:
right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})

In [83]:
left

   key  lval
0  foo     1
1  bar     2

In [84]:
right

   key  rval
0  foo     4
1  bar     5

In [85]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  bar     2     5

In [86]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)

In [87]:
df

     A      B         C         D
0  foo    one  2.987338  0.565646
1  bar    one  0.233256  0.315680
2  foo    two -1.307917  0.478150
3  bar  three  0.730553  0.470827
4  foo    two -0.320090  0.583256
5  bar    two  1.204583  0.093438
6  foo    one  0.415041 -0.609644
7  foo  three -0.589376 -0.467423

In [88]:
df.groupby("A")[["C", "D"]].sum()

            C         D
A
bar  2.168392  0.879946
foo  1.184995  0.549985

In [89]:
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]

In [90]:
index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

In [91]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

In [92]:
df2 = df[:4]

In [93]:
df2

                     A         B
first second
bar   one    -0.785902  1.828797
      two    -0.590360 -0.309325
baz   one     0.419874 -1.457843
      two     0.215136  0.382746

In [94]:
stacked = df2.stack(future_stack=True)

In [95]:
stacked

first  second
bar    one     A   -0.785902
               B    1.828797
       two     A   -0.590360
               B   -0.309325
baz    one     A    0.419874
               B   -1.457843
       two     A    0.215136
               B    0.382746
dtype: float64

In [96]:
stacked.unstack()

                     A         B
first second
bar   one    -0.785902  1.828797
      two    -0.590360 -0.309325
baz   one     0.419874 -1.457843
      two     0.215136  0.382746

In [97]:
stacked.unstack(1)

second        one       two
first
bar   A -0.785902 -0.590360
      B  1.828797 -0.309325
baz   A  0.419874  0.215136
      B -1.457843  0.382746

In [98]:
stacked.unstack(0)

first          bar       baz
second
one    A -0.785902  0.419874
       B  1.828797 -1.457843
two    A -0.590360  0.215136
       B -0.309325  0.382746

In [99]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)

In [100]:
df

        A  B    C         D         E
0     one  A  foo -1.553394 -1.946865
1     one  B  foo  2.100647  0.223351
2     two  C  foo  0.361101 -0.348832
3   three  A  bar  1.118986 -0.955641
4     one  B  bar -0.283449  2.400776
5     one  C  bar -1.083485 -0.589585
6     two  A  foo  1.487353 -0.760732
7   three  B  foo  0.741687  0.622085
8     one  C  foo -1.224395 -0.711240
9     one  A  bar  0.564601  2.069838
10    two  B  bar -0.511628  0.552838
11  three  C  bar -1.990092 -1.195798

In [101]:
pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"])

C             bar       foo
A     B
one   A  0.564601 -1.553394
      B -0.283449  2.100647
      C -1.083485 -1.224395
three A  1.118986       NaN
      B       NaN  0.741687
      C -1.990092       NaN
two   A       NaN  1.487353
      B -0.511628       NaN
      C       NaN  0.361101

In [102]:
rng = pd.date_range("1/1/2012", periods=100, freq="s")

In [103]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [104]:
ts.resample("5Min").sum()

2012-01-01    25857
Freq: 5T, dtype: int64

In [105]:
rng = pd.date_range("3/6/2012 00:00", periods=5, freq="D")

In [106]:
ts = pd.Series(np.random.randn(len(rng)), rng)

In [107]:
ts

2012-03-06   -0.245062
2012-03-07    1.007680
2012-03-08    1.011964
2012-03-09   -0.859933
2012-03-10    1.184461
Freq: D, dtype: float64

In [108]:
ts_utc = ts.tz_localize("UTC")

In [109]:
ts_utc

2012-03-06 00:00:00+00:00   -0.245062
2012-03-07 00:00:00+00:00    1.007680
2012-03-08 00:00:00+00:00    1.011964
2012-03-09 00:00:00+00:00   -0.859933
2012-03-10 00:00:00+00:00    1.184461
Freq: D, dtype: float64

In [110]:
ts_utc.tz_convert("US/Eastern")

2012-03-05 19:00:00-05:00   -0.245062
2012-03-06 19:00:00-05:00    1.007680
2012-03-07 19:00:00-05:00    1.011964
2012-03-08 19:00:00-05:00   -0.859933
2012-03-09 19:00:00-05:00    1.184461
Freq: D, dtype: float64

In [111]:
rng

DatetimeIndex(['2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
               '2012-03-10'],
              dtype='datetime64[ns]', freq='D')

In [112]:
rng + pd.offsets.BusinessDay(5)

DatetimeIndex(['2012-03-13', '2012-03-14', '2012-03-15', '2012-03-16',
               '2012-03-16'],
              dtype='datetime64[ns]', freq=None)